# Generated by Django 5.2.14 on 2026-05-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_car_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='damage_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='license_back',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='license_front',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
