# Generated by Django 5.2.14 on 2026-05-25 09:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_booking_damage_report_booking_license_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING_VENDOR', 'Pending Vendor Acceptance'), ('APPROVED', 'Active'), ('REJECTED', 'Rejected')], default='PENDING_VENDOR', max_length=20)),
                ('created_by', models.CharField(choices=[('ADMIN', 'Admin'), ('VENDOR', 'Vendor')], default='VENDOR', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='car_rental.car')),
            ],
        ),
    ]
