# Generated by Django 5.2.14 on 2026-06-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
